#!/bin/bash

CP=/usr/share/java/reinforce/reinforce.jar
CP=${CP}:/usr/share/java/reinforce/snakeyaml.jar
CP=${CP}:/usr/share/java/apache-ivy/ivy.jar
CP=${CP}:/usr/share/java/junit.jar
CP=${CP}:/usr/share/java/hamcrest-core.jar

"${JAVA_HOME}/bin/java" -cp "${CP}" org.msyu.reinforce.Main "$@"
