#!/bin/bash

_rein() {
    local cur targets
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    targets=$(
    	find -L reinforce -mindepth 1 -maxdepth 1 -type f -name "*.yaml" -printf "%P\n" |
    	sed 's/.yaml$//'
    )
    COMPREPLY=( $(compgen -W "${targets}" -- ${cur}) )
}

complete -F _rein rein
